import { getModel } from "../config/llmModels.js";
import { generatePpt } from "../utils/generatePpt.js";
import deductCredits from "../utils/deductCredits.js";
import { checkAgentLimit } from "../config/agentlimit.js";

export const pptAgent = async (state) => {
    try {
        if (!state.userId) {
            throw new Error("User ID is missing");
        }

        await checkAgentLimit(
            state.userId,
            "ppt"
        );

        const llm = await getModel("ppt");

        const prompt = `
You are an expert presentation writer.

Return ONLY valid JSON.

Do NOT return markdown.
Do NOT return explanations.

Structure:

{
    "title": "",
    "subtitle": "",
    "slides": [
        {
            "title": "",
            "points": []
        }
    ]
}

Generate 5-8 slides.

Each slide should have 3-6 concise bullet points.

Topic:

${state.prompt}
`;

        const res = await llm.invoke(prompt);

        let data;

        try {
            data =
                typeof res.content === "string"
                    ? JSON.parse(res.content)
                    : res.content;
        } catch {
            throw new Error(
                "AI returned invalid PPT JSON"
            );
        }

        if (
            !data?.title ||
            !Array.isArray(data?.slides)
        ) {
            throw new Error(
                "Invalid PPT data generated by AI"
            );
        }

        const pptBuffer =
            await generatePpt(data);

        const creditResponse =
            await deductCredits(
                state.userId,
                "ppt",
                state.sessionId
            );

        const credits =
            creditResponse?.remainingCredits ??
            creditResponse?.credits ??
            state.credits;

        const artifact = {
            type: "ppt",
            title:
                data.title ||
                "Generated Presentation",
            subtitle: data.subtitle || "",
            data,
            generated: Boolean(pptBuffer),
            credits,
        };

        return {
            ...state,
            aiResponse: `# PPT Generated

**${data.title}**

Presentation generated successfully.
`,
            artifacts: [
                ...(state.artifacts || []),
                artifact,
            ],
            credits,
        };
    } catch (error) {
        console.error(
            "PPT AGENT ERROR:",
            error?.data ||
            error?.response?.data ||
            error?.message
        );

        throw error;
    }
};